spring:
  application:
    name: ${AUTH_SERVICE_NAME}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: ${AUTH_SERVICE_PORT}
  error:
    include-stacktrace: never
    include-message: always

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true

services:
  storage:
    name: ${STORAGE_SERVICE_NAME}

security:
  auth:
    seed:
      admin-email: ${ADMIN_EMAIL}
      admin-password: ${ADMIN_PASSWORD}
      user-email: ${USER_EMAIL}
      user-password: ${USER_PASSWORD}

    jwt:
      issuer: ${JWT_ISSUER}