spring:
  application:
    name: ${STORAGE_SERVICE_NAME}

server:
  port: ${STORAGE_SERVICE_PORT}
  error:
    include-stacktrace: never
    include-message: always

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true

integration:
  s3:
    region: ${S3_REGION}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    keys-bucket-name: ${S3_KEYS_BUCKET_NAME}

security:
  rsa:
    private-key-path: ${RSA_PRIVATE_KEY_PATH}
    public-key-path: ${RSA_PUBLIC_KEY_PATH}